### ISSUE TITLE
The script doesn't run in the Nitrotype website

### ISSUE THREAD

**Issue by TheRealKinglogic** [PrabhakarRai/nitro-type-hack-bot#1]
The script doesn't run in the website, and so it doesn't type out the words. The exe is working though.

**Comment by PrabhakarRai** [comment]
Script runs on racing page only, so to see it working, go to race page and click on Tampermonkey icon, you will see this running.
However, to type automatically using bot, you need the exe also. Script alone doesn't do any typing.
