### ISSUE TITLE
It doesn't detect the letters properly. Please fix.

### ISSUE THREAD

**Issue by billyBob456** [PrabhakarRai/nitro-type-hack-bot#7]
Example: It detecs this: Thisw trip exntails nonsftop white water qrapids, narrnow passageowayS<T Anhbdi ssteep drropsx, g. You can tell that that's not the right text.

**Comment by billyBob456** [comment]
Could you maybe decode the JS and maybe I can find a fix with a pull?

**Comment by PrabhakarRai** [comment]
It is correct detection. Thisw is This, trip is trip, nonsftop is nonstop, and so on.
The extra characters are added for error generation. Set accuracy to 100 and you will get all words correct.

**Comment by billyBob456** [comment]
It still doesn't work. It fixed the detection problem, but it doesn't type the words.
