### ISSUE TITLE
Doesn't type anything...

### ISSUE THREAD

**Issue by billyBob456** [PrabhakarRai/nitro-type-hack-bot#8]
![image](https://user-images.githubusercontent.com/86028017/145920136-6253c437-01fd-49c9-a072-f926168ee662.png)
It says its "completed the mission" when the race is done, but it's not done. I just got disqualified because it wouldn't type. Maybe you could try it yourself. Because for me, this is what happens.

**Comment by billyBob456** [comment]
![image](https://user-images.githubusercontent.com/86028017/145920515-3e1ecf2d-814d-4071-9462-06d6f2d814a6.png)
Another example. This time it's an Extracted, uncompressed file. The other was Compressed. This time it actually types (I think it's typing the wrong ones) and uses nitro, but still doesn't work.

**Comment by billyBob456** [comment]
Could you please fix this as soon as you can, or tell me if you're working on a fix. Thanks!

**Comment by billyBob456** [comment]
Are you going to fix this?  Or should I delete the files? Please let me know. I need space on my computer.

**Comment by oslasher** [comment]
idk

**Comment by PrabhakarRai** [comment]
Tool is working properly. However, you are not using it in correct way, hence, the error. Go through step be step guide provided at www[dot]theprabhakar[dot]in
